version: '3'
services:
  vobysbot:
    image: discorbot:x86
    ports:
      - "80:8000"
    volumes:
      - ./config.json:/opt/bot/config.json
      - ./scripts:/opt/bot/scripts
      - ./data:/opt/bot/data
